### ISSUE TITLE
Dogma disparity?

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#102]
My Polaris Legatus Frigate has a capacity of 1,000,000 m^3 while docked, but 0 when undocked!

**Comment by ryllae** [comment]
it's not a type-size error, my Charon has 2M+ m^3 both in and out of space.

**Comment by zhyrohaad** [comment]
polaris (and other non-normal items) are considered 'unpublished", and we follow those guidelines.
when docked, the client does all attribute processing with no help from server.
when in space, server is queried for attributes.
this is why things work (or display) when docked but not in space.

so for things that dont display correctly in space, its because server data is incomplete or the item isnt a 'normal' player item.
in this case, the polaris isnt being processed because the server doesnt load non-published items.

**Comment by ryllae** [comment]
I know it's dev-only, I was mostly opening the ticket to figure out if there's a domga or cargo issue:

I'm using the ship because it's indestructible, and gets around space quickly without `.tr`  What I've been doing is using Groove's tool to adjust the dogma while in space to have capacity - which is curious, since if the server thinks I have a 0 capacity, why don't I get an error from the server when moving stuff into my cargo?

**Comment by zhyrohaad** [comment]
that makes sense.  
i personally use a modified version of a rare player ship for most of my testing (the freki)

when the client sends the 'moving items between cargo' call, it will (sometimes) send a capacity with the call.  
the call used will be one of multiple "move this item to that location" calls depending upon what/where, 
i would think (without actually tracking the code) this call sends the location's capy, which the server is instructed to use, which is why it's not complaining.
