### ISSUE TITLE
You can see your own gateflash

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#126]
Jump through a gate, then look at the gate.  You'll see your own gateflash.  As I recall, the gate should have already flashed before you "arrived", but I could be mistaken?

**Comment by zhyrohaad** [comment]
this is correct behavior.
code is set to allow player to "see" their own jumpin flash.
jumpout is same way.
i dont remember if live runs it this way or not.

**Comment by ryllae** [comment]
Modern gates in TQ got reworked at some point, along with the "system warp" tunnel visuals.  I don't recall ever seeing a flash for myself (which is much smaller these days?) but if you want to leave this as WontFix, it's probably not the end of the world.  

Still, my recollection of Quantum Rise days was that you always saw your own flash on the way out, but the flash happened on arrival before the system loaded in?  Maybe, was a long time ago.

**Comment by zhyrohaad** [comment]
i remember gate flash on both sides.

on the code side, here is how it runs.......
client calls `jump`
server processes jump, sets timer (3-5s)   there is note in code to set this timer >3s to allow player to see their jumpout flash
gate flash is sent to "from" gate
timer hits, new system is queried and booted if not already active
player ship (et al) is moved to new system (this includes player's pod).
position at gate calc'd, 
ship set invul and cloaky.  (the code is there...dunno why it's not working as noted in #?)
bubble created if needed
ship placed in bubble.
gate flash sent to "to" gate for all players in bubble.  as 'jumper' is now in bubble, they get the flash also.
jump process competed

so, it' seems to be a non-issue at this point.   
doesnt really affect gameplay, so we can take it out or leave it in.
from an RP pov, the ship doing the jump should see neither flash, as they are "inbetween" states when the jump data is sent and received.....they ARE the flash.
its in there because the original dev/writer of this system thought it would be neat to see flash on both sides.

**Comment by ryllae** [comment]
So it's either Working as Intended or WontFix, that's fine.  Mark it as such, feel free to close.

**Comment by zhyrohaad** [comment]
im gonna say "Working as Intended" here.

**Comment by zhyrohaad** [comment]
I have thought this over after closing.
From rp pov, ship will be "transmitted" to the "to gate" using the gateflash of the "from gate".  There should be no flash from a gate receiving the transmission; only the gate sending it.
Gateflash on the "To Gate" has been removed, yet pilot will still see their own flash when jumping.

**Comment by ryllae** [comment]
I think that's better too.
