### ISSUE TITLE
After jumping, ships should be cloaked and invulerable for some amount of time

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#127]
I don't recall the exact mechanic, but I know it's totally unimplemented so far.

**Comment by zhyrohaad** [comment]
no, that's been working for years.
the cloak is 30s and invul is 15s for jumping.  cloak is removed on any movement (except stop) or offensive module activation.
invul from undock is 20s.  removed on any movement (except stop) or offensive module activation.

***edit***
wow, cloak isnt working, but invul is.
theres' no telling what all is currently  broken, but i'll have to test my updates on main server, because most of this is working on dev server.

**Comment by zhyrohaad** [comment]
touch

**Comment by ryllae** [comment]
Confirmed on dev `eb777b`: you aren't cloaked after a jump.  Invul works after undock.

**Comment by zhyrohaad** [comment]
after looking over this, the call to `Cloak()` was removed and i cant find when or why.
this has been corrected.

**Comment by ryllae** [comment]
Working.

**Comment by ryllae** [comment]
I was testing #125 and encountered a mysterious regressions on cloaking:

Have two ship undock and head to the local gate.  Jump them both at the same time, they came out cloaked as expected.  I immediately had both return to the gate and jumped again.  When back in the starting system, one ship was cloaked, but appeared on the Overview of the other (oops?).  The other ship was not cloaked (oops!).   Continuing to jump back and forth didn't show a particular pattern that I could discern, but usually jumping *back* was a most broken?

**Comment by zhyrohaad** [comment]
yep.  found it
bubble bcast checks for cloaked ships werent working right.
fixed and updated

**Comment by zhyrohaad** [comment]
fixed and updated.

**Comment by ryllae** [comment]
#135 makes this issue difficult to test, but in the one time I jumped there and back successfully, I wasn't cloaked on return.

**Comment by zhyrohaad** [comment]
this ties into bug #135 with timers and checks.
working on this with others

**Comment by zhyrohaad** [comment]
fixed and main updated

**Comment by ryllae** [comment]
Better.
