### ISSUE TITLE
Infinite Improbability Drive: everything is 0m away, can jump instantly

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#135]
While testing https://github.com/zhyrohaad/AlasiyaEvE/issues/127, I warped to the Ekura gate, jumped both toons.  After jumping, all celestial objects in the overview are listed as 0m away, my ship and bubble didn't load.  I immediately jumped back to Amsen.  Ship A appeared without cloaking, but the bubble loaded correctly.   Ship B returned to Amsen, with all objects at 0m, not loaded.  I was then able to select *ANY* gate, and immediately jump, because I'm apparently 0m from everything.  This is great for hauling!

Calling `.update` twice in a row appeared to fix things, until I jumped again.

**Comment by ryllae** [comment]
PS I hope you've read the Hitchhiker's Guide...

**Comment by zhyrohaad** [comment]
DON'T PANIC
"now, if we only understood what the petunias meant..."
im pretty sure it had nothing to do with thanking us for the fish.  ;)

**Comment by zhyrohaad** [comment]
ahhhh.
found it.
the player wasnt getting new system data after jumping.
none of the checks were set right to prevent this.
testing fix.

****  edit  ****
this is a good one.
not only were the checks invalid, but the timers for ALL Ballpark/Destiny Init() settings were inconsistent as well.
this includes Cloak, Invul, Jump, Ballpark and Login.
im rewriting all timer settings and checks, as well as reworking timer logic.
currently have cloak, invul, and jump timers and logic consistent.
working on ballpark and login.

as a bit of background.....
invul and cloak methods set/update/send applicable data based on a timer.
ballpark sets destiny and some ship variables and decides when to send System SetState data to client
login is set to allow client and server time to get everything initialized and sorted.  it also sets invul, cloak and ballpark timers
jump sets invul and cloak timers, then after player is transferred to new system, jump will set ballpark timer.


**** edit again ****
so, the ACTUAL error in this case is the ship jumping is set to 'cloak' during the jump method, before adding to stargate bubble in new system.  this is to prevent a 'blip' on the radar of anyone in the gate's bubble.  (and warning campers about fresh meat).
at one point in history, i removed the (supposedly redundant) check of inserting the ship back into the state data before sending to client.
because of this, the state data for new System is sent to client WITHOUT their ship in it...which causes client to freak out.
that's fixed, and i guess im just reviewing timers and other checks 'just because'.  ;)

**Comment by zhyrohaad** [comment]
fixed and main is updated

**Comment by ryllae** [comment]
appears to be fixed, but I also get an update when entering warp that I shouldn't: #141   not sure if related.
