### ISSUE TITLE
GPL Release

### ISSUE THREAD

**Issue by jdhirst** [zhyrohaad/AlasiyaEvE#137]
Hi,

The upstream codebase being modified in your private fork is open source under the GPL. In the spirit of this, improvements/modifications made should be made available to the open source community. 

Would you please consider contributing to the open source project or at the very least releasing your modified version?

I am looking for a project and am interested in working on the evemu emulator.

Thanks!

**Comment by tercenya** [comment]
As I understand it, the core team had some disagreements, parted ways a while back, and Alasiya became a hard fork, and hasn't been open sourced [yet].  I don't know the terms of the parting and relicensing, or if people want to reopen those wounds, but you're welcome to find the relevant parties.

That said, there have been several contributions back to the open repo that were inspired in Alasiya: see https://github.com/evemuproject/evemu_server/commits/master. That said, the https://github.com/evemuproject/evemu_server is still current and open to commits, there's an active Discord group for it.  Honestly, it needs a lot of love, if not a complete rework :shrug:

If you're looking for places to do work, you might also consider some of the other recently active related projects? https://github.com/Almamu/EVESharp/

**Comment by jdhirst** [comment]
@tercenya Interesting, thanks for the information! Is EVESharp related to the EVEmu old apocrypha version? 

I hadn't wanted to contribute to EVEmu if Alasiya had fixed many of the current issues with EVEmu, and therefore duplicate work. If we had Alasiya as an open source project, I would imagine there would be many people happy to work on it in the community. However the state that EVEmu is in right now makes that a hard pill to swallow imo.

**Comment by THUNDERGROOVE** [comment]
> Is EVESharp related to the EVEmu old apocrypha version?

No, but it targets the Apocrypha client.

As a contributor to Alasiya I would wholeheartedly recommend looking into EVESharp if you have any interest.  It would be a lot cleaner of a start, there's a lot of things that evemu official doesn't handle correctly in it's core in terms of memory management, packet encoding, etc. that are definitely not an easy fix without having a lot of experience in the ways of eve or c++.

I do know that Allan is interested in backporting some of these core fixes while leaving contributions to get the various services working correctly.  I wouldn't expect that soon however.

Alasiya really is Alan's baby, 99% of the nearly 2,000 commits since it was forked are his work and I think respecting his wish to keep it closed is definitely warranted.

**Comment by jdhirst** [comment]
> Alasiya really is Alan's baby, 99% of the nearly 2,000 commits since it was forked are his work and I think respecting his wish to keep it closed is definitely warranted.

I agree, I do respect that, I merely was considering the possibility of leveraging the community with assistance on what is certainly a learning and passion project for all those involved.

> > Is EVESharp related to the EVEmu old apocrypha version?
> 
> No, but it targets the Apocrypha client.

On another note, regarding EVESharp, I'll certainly take a look, although I don't have any C# experience. For a general question, if starting from scratch, why Apocrypha?

**Comment by zhyrohaad** [comment]
i do commit to the official evemu source.
however, with the lack of required time for proper refactoring and testing, i have not added anything in quite a while.
i have considered releasing my source, and have decided against it.  there is more interest in using my code for personal gain than contributing to the open source of the project.

thanks for your thoughts and comments.
