### ISSUE TITLE
Onlining/offlining modules in space is borked

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#14]
**Describe the bug**
Offlining a module in space *appears* to disable the module, but you can't online it again.  Onlining a module in space has no effect (although the only easy way to even get this choice is to get booted by the server, relog back in space with all your modules offlined for you)

**To Reproduce**
Undock, offline a module.

**Comment by zhyrohaad** [comment]
modules (ex. caps) were 95% complete at one time.
this will be high priority

**Comment by zhyrohaad** [comment]
turns out the "in space" part is negligible.
module online attribute isnt very consistent.
am working on the problem, and fixing as needed.

**Comment by ryllae** [comment]
Retested:  If you undock with modules offline, you can bring them online and they work (though I thought that step was supposed to consume cap?)  So that's an improvement.

If you offline a module in space, you can't bring it back online again.

**Comment by ryllae** [comment]
Alas, if use "Strip Fitting" to offline all modules, you still can't online them in space.  Still borked.

**Comment by ryllae** [comment]
Also, offlining a Shield Extender in space neither reduces your shields nor frees up resources.  Ergo "offlining doesn't work at all really".

**Comment by zhyrohaad** [comment]
yes, without the assistance of a drydock or cap ship with a fitting hangar, onlining a module will consume 75% of your total capacitor.   however, this is currently disabled while we're still testing and whatnot.

so, based on your testing, i need to go over module code a bit more to look at some other details, mainly things i havent thought of.

i will post when i have it fixed and updated.

**Comment by zhyrohaad** [comment]
when in space and using fit window, modules online/offline correctly (and update ship attributes accordingly).
when rclick on module icon (on HUD), client sends a `Deactivate` call, which is NOT coded to check for or process online/offline.
i wasnt aware the client was sending this call for that action.
i'll update server call code to test for and take appropriate actions.

**Comment by zhyrohaad** [comment]
this particular call is fixed, but in my testing, i have found many more things using the `Deactivate` call that i wasnt aware of.
most of these are negligible, but some will allow things to not work right.  as they are seldom used in this case, i will work on them later.  

however, for the case of this particular bug, main is updated.

**Comment by ryllae** [comment]
I'm curious to the distinction, but it may be relevant:  if you offline a module that is actively in a cycle (say, Adaptive Invuln Field), it correctly disables itself after the cycle is complete (I see the shield resists go down).  Attempting the reactivate the module gives a "this module is offline" error message.  BUT right clicking only gives you the option to *offline* it - have to offline it a *second time* before you can online it.

Otherwise the previous bugs are much improved.

**Comment by zhyrohaad** [comment]
there are multiple calls to a couple of ship systems (on server) that deal with modules.
i havent totally gone thru client code to follow all the calls, so i can only give you what i know.
most "disable" calls seem to be intended to immediately stop and offline the module.  i have these coded to finish current cycle, then offline, as it makes things simpler, and imho, follows a more logical path.....the ship system cannot just 'stop', it has to finish cycle first.   however, sometimes the client dont agree with this, and your findings are proof of this.  

now, as there are multiple functions for modules (online, offline, activate, load, etc), there are just as many ways to call these functions, including HUD, fit window, <ctrl>+<key>, rclick space item, and even from the overview.   also you can disable a module by rclick on the module icon on target.
while all of these are expected to provide the same functionality, they all have different calls to multiple server systems.  
trying to get these to provide this same expected functionality from multiple calls with multiple identifiers has been tricky, and ofc im sure i have missed some.
for the most part, the "on", "off", "start" and "stop" calls work from most of the calls. 

for modules in particular, the fit window is the most accurate.  its' the one i use for testing, with hud being second.

because of this, keeping the module attributes (online state, current time, etc) sync'd as been crazy, and sometimes they get missed.   only recently, i have realized the online state wasnt being tracked properly, which is why you get conflicting msgs from various systems.

something else to note here.....modules arent the only system that works like this.....MOST client systems have multiple server system calls like this.

now, hopefully this has explained the clients processing a bit, and why some things are working one way, but not another, which is why i want to know the whats and hows when something doesnt work and how you tried to use it.

**Comment by zhyrohaad** [comment]
any updates on the status of this bug?

**Comment by ryllae** [comment]
Ah, I'll make a distinction between using the fitting window and the UI.  All tests here were done in space:

- Using the UI to offfline on a module that is mid-cycle still requires a 2nd "offline" before it can be onlined again in the UI.
- Using the fitting window (in space) to offline a module that is midcycle lets it run forever, while consuming no resources or cap 😃 🥇  This allows for some FANTASTIC fits in the mid slots.   Infact, once you have trigger this "feature", offlining it in the UI doesn't stop the cycle. Trying to stop the module using the UI causes the module to "hang", while still providing you benefits and consuming no resources.
- Onlining a module using a fitting window (in space) has no blinking start uptime (as it would if you used the UI).

**Comment by ryllae** [comment]
Another misfeature: if you online or attach a module in space that changes your damage or health (say, you online or fit a Large Shield Extender via the fitting panel), other players who have you targeted do not receive an update with your new total HP / damage %.  If they retarget you, or activate a module such a remote shield booster, they will get an update correctly.

**Comment by zhyrohaad** [comment]
a bit of clarification here.....
a currently-cycling module can be instructed to 'offline' from the ui.  after it completes its cycle, it will offline?  or do you have to offline it again to get desired results?
at this time, only miners are coded to stop mid-cycle (which still takes a bit of time to stop).  other modules will complete current cycle before stopping (effectively turning repeat off).

so, by offlining a module thru fit window, the module DOESNT stop?
then, using ui to offline same module a second time causes the bug?

from your testing, it look like i have quite a bit of logic to look over with modules.
these are things i haevnt thought of to try.

**Comment by ryllae** [comment]
> a currently-cycling module can be instructed to 'offline' from the ui. after it completes its cycle, it will offline? or do you have to offline it again to get desired results?

After it completes its cycle, It's offline (greyed out in the UI).  You cannot activate it again.  But if you right click in the UI, you don't get the option to "Online" it.  Instead you have the option to "offline" a second time.

> at this time, only miners are coded to stop mid-cycle (which still takes a bit of time to stop). other modules will complete current cycle before stopping (effectively turning repeat off).

Seems like the correct behavior.  My point here is that when the cycle is done, the module is "off", but you have to offline it a second time before you can online it again.   THis was tested with Inulv. Fields and Shield boosters.

> so, by offlining a module thru fit window, the module DOESNT stop?

Yup.  A Invul. Field will run forever, providing resists forever, but consumes no CPU/PG/cap.   And it's greyed out in the UI, and you can't really interact with it properly.

> then, using ui to offline same module a second time causes the bug?

If you start playing around with a module that's "running forever while offline", the UI gets very confused, and it's not clear that you can start or stop it again by any means.

**Comment by zhyrohaad** [comment]
ok, so weird shit with modules.
will check this after current inventory bug chase.

**Comment by zhyrohaad** [comment]
ok...looked at modules.
i can duplicate all mentioned errors, as well as a few more.
this will be a rather lengthy process, as current system is already complicated, and 'fixing' these checks will complicate it quite a bit more.

will update when i have something to report.

**Comment by zhyrohaad** [comment]
found and fixed multiple errors with modules, mostly due to different calls based on what part of ui you're using (fit window, hud, overview, target)
currently testing fix.

because it was *MY* complicated shit, i was able to quickly find and integrate multiple calls and fixes  for this without too much trouble....so it didnt take near as long as i thought it would (but there is still work to be done on the module system as a whole)

**Comment by zhyrohaad** [comment]
main updated

**Comment by ryllae** [comment]
Found a few fitting oddities, but this bug looks good so far.  I'll call it done.
