### ISSUE TITLE
Undocking causes modules to be onlined that shouldn't be.

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#15]
**Describe the bug**
Modules that are offlined (particuarlly for lack of resources) will often appear online when you undock.  They have to have been onlined at least once at some point?

**To Reproduce**
Equip a Halk with a 1MN MWD, then a 10MN Afterburner.  offline the first, online the second.  Undock, and both are online (which is impossible to fit on powergrid).    Activating the MWD causes Destiny issues, as your location goes NaN, followed by a server error?

![Capture14](https://user-images.githubusercontent.com/51723245/59395201-57b2ad00-8d48-11e9-948f-c413b679e7b3.PNG)

**Comment by zhyrohaad** [comment]
whoa
thats a good one.
error is thrown from bubble thinking your location is wrong.....which it is, as your coords are NaN.
and the error number is wrong, so that another thing to fix.  (nbd)

however, you should not be able to fit both ab and mwd on same ship, much less online them both.
this will be fairly easy to fix, but will take a while to update main, as the systems involved are being updated for other things, which all ties in to the db wipe, which will be later.

**Comment by zhyrohaad** [comment]
tested this on dev server.   
here's my findings:
1) modules are limited by group, according to item's group fitting limitations
2) fitting a 10mn mwd to rifter, using moderate skills (lvl 2-3), does not have enough pg to online the module while docked.  
3) fitting a 1mn ab to said rifter, will online module as expected.
4) undocking with the 10mn mwd, the server sends an error msg stating the ship doesnt have enough pg to online the module.

based on these finding, this is a null issue concerning the module onlining when undocking.
after main server is updated, will need this tested before i consider this issue closed.
i will post here when main server is updated.

**Comment by zhyrohaad** [comment]
this fix has been pushed to main server.
please test again to verify

**Comment by ryllae** [comment]
Although you worked around the example I gave fixing GroupFits, I was able to duplicate the same problem previously using Shield Extenders instead, getting twice as many online as there should have been.

It looks modules are no longer onlined automagically when undocking, but given the current state of https://github.com/zhyrohaad/AlasiyaEvE/issues/14 (re: onlining and offlining modules in space and fitting), I can't actually test this yet.

**Comment by zhyrohaad** [comment]
i will look into this a bit more.
the client sends a list of modules to be onlined when undocking, and from what ive seen, this is working properly.
however, because of the skill effects errors, this may cause a problem with ship resource checks.
it will need retesting once main is updated with fixed effects code.

**Comment by zhyrohaad** [comment]
fx code is updated and working correctly again, and i have tested modules online/offline and undocking automagically onlining correct modules.
this appears to be working right now.
also, while working this, i have made some modifications to module online/offline code
modules online state is now saved and recalled correctly.
i have also made some other adjustments on module code for testing and setting online states,

so, as stated, on my last update, i was able to work around the listed bug by not allowing multiple modules of same group.
this time, the actual test i used was to fit 8 shield mods and online every-other-one.
after undocking, every other module was online, as i had set them.
this test was conducted with multiple modules and ships and multiple times, and all passed.

main is updated with fixed code.
pls test again and report findings.

**Comment by ryllae** [comment]
Looks good to me too.  This also fixed onlining phantom equips as well.
