### ISSUE TITLE
Strip Miners aren't limited to Mining Barges

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#25]
Equipping 8 strip miners on a Hulk runs out of CPU too quickly. https://github.com/zhyrohaad/AlasiyaEvE/issues/23 so why not step things up a notch and just put 8 strip miners on a fully fit Rokh?  Probably close to 50K EHP, and with 5 mining laser enhancements, should out strip the barge.  Gonna need bigger cans.

![Capture10](https://user-images.githubusercontent.com/51723245/63572749-41477f80-c549-11e9-92cd-ced5366134ec.PNG)

But if you're more casual, you could mine in style, perhaps a Rifter or a Heron...
![Capture8](https://user-images.githubusercontent.com/51723245/63572774-515f5f00-c549-11e9-8904-675487351a50.PNG)
![Capture4](https://user-images.githubusercontent.com/51723245/63572789-591f0380-c549-11e9-95d2-abe6c436466a.PNG)

**Comment by ryllae** [comment]
Oddly enough, you can keep dragging additional Strip Miners to the Rokh even though you used up all your high slots, until you completely run out of CPU.  They appear to be equipped, but you have no way to activate them in space. That's too bad, could have fit 12 or 14 strip miners instead.

**Comment by zhyrohaad** [comment]
now there's something you dont see everyday.
nor have i even considered trying it, so nope....im fairly sure there are no checks for any of that.
well...not yet.  ;)

ok, so with the rifter......do they work?   can you mine with them?

**Comment by zhyrohaad** [comment]
in my testing, i was able to put 2 strip miners on a ......  forgot the name.  minmatar noob ship.
anyway, they worked.  lol.
my cargo capy test works, also, so that was at least one positive out of it.

now, i have found the error.  the module code had been written, but wasnt being called correctly.  this must have been during one of my 'updates'. 
anyway, this is fixed and main is updated.

retest when you get time, pls.

![2019 08 23 21 58 29](https://user-images.githubusercontent.com/6365054/63631717-e36e7280-c5f0-11e9-8c82-1742f31bf79f.png)
![2019 08 23 22 00 48](https://user-images.githubusercontent.com/6365054/63631728-f7b26f80-c5f0-11e9-9f5d-3bd7c2cd0bd5.png)

**Comment by ryllae** [comment]
I was going to make a video, but you beat me to it. Though the Impairor takes the cake, I think.

Look good, I get the correct error message when trying to fit a non-barge.

**Comment by zhyrohaad** [comment]
as a note, this fix applies to ALL type-limited modules and ships, not just strip miners and barges.
while listed as a 'fix', it is more accurate to say i corrected the existing call not being processed properly.
so, yeah, it's a fix.
