### ISSUE TITLE
Onlining a tower is not persisted across a server crash

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#66]
Launch a control tower (requires effort until https://github.com/zhyrohaad/AlasiyaEvE/issues/60 is resolved).  Anchor it, wait 30 minutes.  Online it.  Crash the server by any means (say https://github.com/zhyrohaad/AlasiyaEvE/issues/65).  Relog in, and the tower is no longer in the online countdown.

**Comment by zhyrohaad** [comment]
there are many POS systems incomplete at this time.
this work will resume at a later date (tba)

**Comment by zhyrohaad** [comment]
will look into timer and other supposedly 'saved' data possibly soon.

all tower testing shows save/retrieve working properly.
have not tested pos modules or anything other than towers.

main updated with current code.

**Comment by zhyrohaad** [comment]
the key word here is "crash"
that's the whole point, tbh.
when data is corrupted enough to cause a crash, NOTHING is saved, because we cannot verify the validity of the current data state.
this is something i've worked on for a while (on and off) and have not come up with a solution.

so, at this time, this is expected behavour.

as a side note, i've tested multiple timers across an actual shutdown, and they persist (except skills, which STILL is kicking my ass)
