### ISSUE TITLE
Anchoring a control tower creates a new bubble, and changes its location

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#67]
Launch a control tower by a moon.  Click Anchor.  The control tower immediately appears at a distant location, and during anchoring, you warp to the new bubble.  This may be the intended behavior for Crucible?

**Comment by zhyrohaad** [comment]
not for crucible, but IS for alasiya.
because the tower is moved (by some mysterious force in the system) to place itself on a new grid, your ship automatically follows to the new location, due to communication between ship, CT, and system controllers.

side note....because of this behavior (which is intended), you can tell if a moon has a tower anchored when warping to it.
here's how.
all warp-to points on moons go to same relative location (planets also).   this is designed to APPEAR to be in same spot for moons and planets (the object appears the same size for both.  was quite a feat).  when warping to moon, you will go to 'bottom left' of moon, which is actually gonna be the closer point to the star.  (lower hemisphere, towards inside of solar system)
when a tower is anchored, the warp-in point changes to the upper right of the moon, and will be on the edge of the CT's bubble.  this is just barely outside of the CT range, which will give you an escape route before being targeted/attacked if the CT is hostile.

because of this behavior, you will notice your final location in the last few seconds of warp, which will give you a few extra seconds to find a warp target if you need to escape quickly.

**Comment by zhyrohaad** [comment]
so, this isnt a bug, per se, so it will be closed.
one day i'll put the warp info on the forums, unless someone else beats me to it.
