### ISSUE TITLE
Docking while acquiring mutual locks on a hostile causes a segfault

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#75]
Undock a large ship (say, a Raven Navy Issue).   `.spawn 13645 20`.  Immediately start acquiring a lock on several targets.  As soon as they attempt to target you back, dock up.  <crash>.

Not sure if the crashing is coming from me or them.

**Comment by zhyrohaad** [comment]
whoa....wtf?
there is code in targetMgr that checks for presence of target.
systemMgr, bubbleMgr and destinyMgr verify ALL object positioning (yes, 3-way independent redundancy), and communicate with all other managers when changes occur.
this means the error you report should never happen.
since you're reporting it, i have some major problems in my manager communication or *something else*
hell, even when a ship docks, it tells EVERYBODY it's docking, so this should NEVER happen.

i'll look at server logs and run some tests and report back when i know something

**Comment by zhyrohaad** [comment]
found problem and coded fix
main updated
the 'ship docking' code was commented out with a note calling to "fix this shit later"

nice.

**Comment by ryllae** [comment]
> zhyrohaad: ![](https://i.imgur.com/wimz70n.jpg)

Better now.

**Comment by ryllae** [comment]
Same problem.  Spawn some rats, let them start targeting you, dock up for a segfault.  Works ok if they have *acquired* the lock.

**Comment by zhyrohaad** [comment]
Ok so in this case, it's the TargMgr that isn't getting the "I'm docking, asshole" msg.
I'm not sure if that particular action is passed to targeting system or not.
Now that I think about it, it very well **should** be, cause players can target docking ships too.
This also needs more work.

**Comment by zhyrohaad** [comment]
as noted in #108, this seems to be working as intended, and main server has been updated.

**Comment by ryllae** [comment]
Looks good again.
