### ISSUE TITLE
Receiving ore from a strip miner causes a full screen flash and refresh

### ISSUE THREAD

**Issue by ryllae** [zhyrohaad/AlasiyaEvE#91]
Start strip mining an asteroid with a hulk.  Right click on your ship, choose "show info".  Also open your cargo hold. Wait for the strip miner cycle to finish.  Each time ore is added, the whole screen will flash, and all information will refresh (complete with 3 exceptions for having a negative remaining insurance time).

Expected: You shouldn't have to requery the state of the universe everytime I get some Veldspar?

**Comment by zhyrohaad** [comment]
Well, ok then.
Not sure what's going on here, but will put it on the list.

**Comment by zhyrohaad** [comment]
found it.
it's based on an open item info window.
that is the only time it happens (for me).
there is a refresh (cant find the exact call) which calls `GetWndData()`, which in turn refreshes all open windows.
among other things, this call updates insurance data, which is why you get the insurance time exceptions.

whether this happens on live, i dont know.
however, at this time, i dont see anything i can do about it, and with the only call i see is to insurance, im gonna say this is a non-issue.
